Description of im
Home > matlab > im.m
im
PURPOSE
im(X) or im(X,[minval maxval])
SYNOPSIS
function im(X,vec);
DESCRIPTION
 im(X) or im(X,[minval maxval])
 Handy function for showing a grayscale image with a colorbar and
 interactive pixel value tool
 Serge Belongie
 20-Aug-2000
 sjb@eecs.berkeley.edu
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
freqest FREQEST - Estimate fingerprint ridge frequency within image block
normalise NORMALISE - Normalises image values to 0-1, or to desired mean and variance
ridgefilter RIDGEFILTER - enhances fingerprint image via oriented filters
ridgefreq RIDGEFREQ - Calculates a ridge frequency image
ridgeorient RIDGEORIENT - Estimates the local orientation of ridges in a fingerprint
ridgesegment RIDGESEGMENT - Normalises fingerprint image and segments ridge region
show SHOW - Displays an image with the right size and colors and with a title.
testfin TESTFIN
SOURCE CODE
function im(X,vec);
% im(X) or im(X,[minval maxval])
%
% Handy function for showing a grayscale image with a colorbar and
% interactive pixel value tool
%
% Serge Belongie
% 20-Aug-2000
% sjb@eecs.berkeley.edu
if nargin==1
   imagesc(X)
else
   imagesc(X,vec)
end
pixval on
title(inputname(1))
colormap(gray)
colorbar
axis('image')