Description of p
Home > matlab > p.m
p
PURPOSE
-----Sub functions-------
SYNOPSIS
function [j,X, Y] = p(img, x, y, i)
DESCRIPTION
-----Sub functions-------
 get pixel value based on chart:
  4 | 3 | 2
  5 |   | 1
  6 | 7 | 8
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
FindOrient Joshua Ibrahim
FindTheta
clean_minutia JI: Removes spikes
extract_finger Author: Joshua Abraham
figures Bibliography
filter_minutia call with thinned, index, minutiae list, x
houghline HOUGHLINE - detects lines in a binary image using common computer vision operation known as the Hough Transform.
pathdef PATHDEF Search path defaults.
roc ROC - Receiver Operating Characteristics.
test_bifurcation Returns if the single ridge in a bifurcation is
trace_path call with thinned, index, minutiae list, x
SOURCE CODE
%-----Sub functions-------
function [j,X, Y] = p(img, x, y, i)
% get pixel value based on chart:
%  4 | 3 | 2
%  5 |   | 1
%  6 | 7 | 8
switch (i)
    case {1, 9}
        Y=y;
        X=x+1;
        j = img(y, x + 1);
    case 2
        Y=y-1;
        X=x+1;
        j = img(y - 1, x + 1);
    case 3
        Y=y-1;
        X=x;
        j = img(y - 1, x);
    case 4
        Y=y-1;
        X=x-1;
        j = img(y - 1, x - 1);
    case 5
        Y=y;
        X=x-1;
        j = img(y, x - 1);
    case 6
        Y=y+1;
        X=x-1;
        j = img(y + 1, x - 1);
    case 7
        Y=y+1;
        X=x;
        j = img(y + 1, x);
    case 8
        Y=y+1;
        X=x+1;
        j = img(y + 1, x + 1);
end